/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.ga4gh.starterkit;

import java.io.IOException;

import javax.naming.ConfigurationException;

import org.apache.commons.cli.ParseException;
import org.ga4gh.starterkit.springconfig.StarterKitSpringConfig;
import org.ga4gh.starterkit.springconfig.services.DrsServiceSpringConfig;
import org.ga4gh.starterkit.springconfig.services.WesServiceSpringConfig;
import org.ga4gh.starterkit.startup.Startup;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.EnableAutoConfiguration;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Import;

@Configuration
@EnableAutoConfiguration
@Import({
    StarterKitSpringConfig.class,
    DrsServiceSpringConfig.class,
    WesServiceSpringConfig.class
})
public class StarterKit {

    public static void main(String[] args) {
        try {
            Startup.startup(args);
            SpringApplication.run(StarterKit.class, args);
        } catch (ParseException ex) {
            System.out.println("Could not parse config file");
        } catch (IllegalArgumentException | IOException | ConfigurationException ex) {
            System.out.println(ex.getMessage());
        }
    }
}
