/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.ga4gh.starterkit;

import java.util.ArrayList;
import java.util.List;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication(exclude = {
    org.ga4gh.starterkit.drs.App.class,
    org.ga4gh.starterkit.drs.AppConfig.class,
    org.ga4gh.starterkit.wes.App.class
})
public class StarterKit {

    public static void main(String[] args) {
        System.out.println("Starting Starter Kit App");
        System.out.println("Going to register services");

        System.out.println("Going to run services");
        // SpringApplication.run(StarterKit.class, args);

        // SpringApplication.run(org.ga4gh.starterkit.drs.App.class, args);

        List<Class<?>> foo = new ArrayList<>();
        foo.add(org.ga4gh.starterkit.drs.App.class);
        foo.add(org.ga4gh.starterkit.drs.AppConfig.class);
        Class<?>[] foobs = new Class<?> [foo.size()];
        foo.toArray(foobs);
        
        SpringApplication.run(foobs, args);
    }
}
